export type FlavourTag =
  | 'bestseller'
  | 'ube'
  | 'kakanin'
  | 'coffee-pairing'
  | 'everyday'
  | 'gifting'
  | 'starter'
  | 'main'
  | 'pasta'
  | 'breakfast'
  | 'hot-drinks'
  | 'iced-drinks'
  | 'frappe'
  | 'non-coffee'
  | 'ensaymada'
  | 'bread'
  | 'cheese';

export type MenuCategory =
  | 'Starters'
  | 'Cheese Bread Bites'
  | 'Cheese Rolls'
  | 'All Day Breakfast'
  | 'Mains'
  | 'Pasta'
  | 'Ensaymadness'
  | 'Hola Bars'
  | 'Hot Beverages'
  | 'Over Ice'
  | 'Holamazing Beverages'
  | 'Non Coffee';

export interface Product {
  id: string;
  name: string;
  description: string;
  longDescription: string;
  price: number;
  priceNote?: string;
  tags: FlavourTag[];
  category: MenuCategory;
  image: string;
  imageAlt: string;
  inStock: boolean;
}

export const PRODUCTS: Product[] = [
  // ── Starters ─────────────────────────────────────────────
  {
    id: 'spam-fries',
    name: 'Spam Fries',
    description: 'Crispy golden strips of spam, fried to perfection.',
    longDescription: 'Crispy golden strips of spam fried to perfection — salty, savory, and dangerously snackable.',
    price: 200,
    tags: ['starter'],
    category: 'Starters',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Crispy golden Spam Fries on a plate',
    inStock: true,
  },
  {
    id: 'kangkoy',
    name: 'Kangkoy',
    description: 'Deep-fried crispy kangkong leaves — a light, crunchy snack.',
    longDescription: 'Deep-fried crispy kangkong leaves served as a light, airy, and crunchy snack. Kapampangan comfort food at its finest.',
    price: 180,
    tags: ['starter'],
    category: 'Starters',
    image: '/assets/photos/493960790_1252744956855690_2268947724127227144_n.jpg',
    imageAlt: 'Hola Kangkoy — deep-fried crispy kangkong leaves served in a basket',
    inStock: true,
  },
  {
    id: 'beef-quesadillas',
    name: 'Beef Quesadillas',
    description: 'Grilled tortillas stuffed with beef, cheese, and spices.',
    longDescription: 'Grilled tortillas generously stuffed with seasoned beef, melted cheese, and spices — crispy outside, hearty inside.',
    price: 240,
    tags: ['starter'],
    category: 'Starters',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Grilled beef quesadillas sliced and plated',
    inStock: true,
  },
  {
    id: 'parmesan-fries',
    name: 'Parmesan Fries',
    description: 'Crispy fries tossed in savory parmesan cheese.',
    longDescription: 'Golden crispy fries tossed in savory parmesan cheese — the perfect salty side or starter.',
    price: 167,
    tags: ['starter'],
    category: 'Starters',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Parmesan-dusted crispy fries',
    inStock: true,
  },

  // ── Hola Cheese Bread Bites (Box of 20) ──────────────────
  {
    id: 'milky-cheese-bread-bites',
    name: 'Hola Milky Cheese Bread Bites',
    description: 'Soft bite-sized bread filled with sweet milky cheese.',
    longDescription: 'Twenty soft bite-sized bread bites filled with sweet, milky cheese. Pillowy, cheesy, impossible to stop at one.',
    price: 333,
    priceNote: 'Box of 20 pcs',
    tags: ['bestseller', 'bread', 'cheese', 'gifting'],
    category: 'Cheese Bread Bites',
    image: '/assets/photos/495569833_1257001529763366_8695173742072615558_n.jpg',
    imageAlt: 'Hola Milky Cheese Bread Bites — bite-sized golden bread bites piled high with grated cheese and cream drizzle in an open yellow Hola box',
    inStock: true,
  },
  {
    id: 'yema-cheese-bread-bites',
    name: 'Hola Yema Cheese Bread Bites',
    description: 'Mini bread bites with rich yema and cheese filling.',
    longDescription: 'Mini bread bites packed with rich, sweet yema and melted cheese — a Filipino classic in every bite.',
    price: 380,
    priceNote: 'Box of 20 pcs',
    tags: ['bread', 'cheese', 'gifting'],
    category: 'Cheese Bread Bites',
    image: '/assets/photos/fp_26528375_yema-cheese-bites.jpg',
    imageAlt: 'Hola Yema Cheese Bread Bites — golden pillowy bite-sized bread bites in an open yellow Hola box',
    inStock: true,
  },
  {
    id: 'assorted-cheese-bread-bites',
    name: 'Hola Assorted Cheese Bread Bites',
    description: 'A mix of your favorite cheese bread bite flavors.',
    longDescription: 'A curated mix of Hola\'s favorite cheese bread bite flavors in one box — perfect for sharing or gifting.',
    price: 387,
    priceNote: 'Box of 20 pcs',
    tags: ['bread', 'cheese', 'gifting'],
    category: 'Cheese Bread Bites',
    image: '/assets/photos/fp_26528379_assorted-cheese-bites.jpg',
    imageAlt: 'Hola Assorted Cheese Bread Bites — golden bread bites packed in an open yellow Hola box',
    inStock: true,
  },
  {
    id: 'spanish-bread',
    name: 'Hola Spanish Bread',
    description: 'Classic soft bread roll with sweet buttery filling.',
    longDescription: 'Classic Filipino Spanish bread — soft, pillowy rolls with a sweet, buttery filling baked to golden perfection.',
    price: 347,
    priceNote: 'Box of 20 pcs',
    tags: ['bread', 'everyday'],
    category: 'Cheese Bread Bites',
    image: '/assets/photos/fp_26528454_spanish-bread.jpg',
    imageAlt: 'Hola Spanish Bread — soft cinnamon-dusted Spanish bread rolls packed in an open yellow Hola box',
    inStock: true,
  },
  {
    id: 'ube-spanish-bread',
    name: 'Hola Ube Spanish Bread',
    description: 'Ube-filled Spanish bread with cheesy goodness.',
    longDescription: 'Fifteen ube-filled Spanish bread rolls with cheesy goodness — vibrant, sweet, and unmistakably Kapampangan.',
    price: 347,
    priceNote: '15 pcs',
    tags: ['ube', 'bread', 'cheese'],
    category: 'Cheese Bread Bites',
    image: '/assets/photos/598527943_1458476646282519_5204967568052804532_n-1.jpg',
    imageAlt: 'Hola Ube Spanish Bread — purple ube bread bites split open to reveal a creamy white filling, dusted with sugar on a cooling rack',
    inStock: true,
  },

  // ── Hola Cheese Rolls (Box of 6) ─────────────────────────
  {
    id: 'cheese-floss-rolls',
    name: 'Hola Cheese Floss Rolls',
    description: 'Soft rolls topped with savory cheese floss.',
    longDescription: 'Pillowy soft rolls topped generously with savory cheese floss — fluffy, cheesy, and absolutely delightful.',
    price: 400,
    priceNote: 'Box of 6 pcs',
    tags: ['bread', 'cheese', 'bestseller'],
    category: 'Cheese Rolls',
    image: '/assets/photos/546456029_1372782538185264_458962016792196231_n.jpg',
    imageAlt: 'Hola Cheese Floss Rolls — six pillowy soft rolls piled with grated cheese floss and cream drizzle inside an open yellow Hola box',
    inStock: true,
  },
  {
    id: 'duo-rolls',
    name: 'Hola Duo Rolls',
    description: '3 pcs ube and 3 pcs double cheese rolls.',
    longDescription: 'The best of both worlds — three ube rolls and three double cheese rolls in one box.',
    price: 373,
    priceNote: 'Box of 6 pcs',
    tags: ['ube', 'bread', 'cheese'],
    category: 'Cheese Rolls',
    image: '/assets/photos/494304853_1257147449748774_7146470878540760849_n.jpg',
    imageAlt: 'Hola Duo Rolls — three classic cream-filled rolls and three purple ube rolls side by side, dusted with powdered sugar on a white plate',
    inStock: true,
  },
  {
    id: 'assorted-rolls',
    name: 'Hola Assorted Rolls',
    description: 'Cheese floss, double cheese, and ube cream cheese.',
    longDescription: 'A box of six featuring cheese floss, double cheese, and ube cream cheese rolls — the full Hola experience.',
    price: 393,
    priceNote: 'Box of 6 pcs',
    tags: ['ube', 'bread', 'cheese', 'gifting'],
    category: 'Cheese Rolls',
    image: '/assets/photos/546331655_1371869878276530_4573038799687110187_n.jpg',
    imageAlt: 'Hola Assorted Rolls — cheese floss, cream cheese, and ube rolls on a wooden board, split open to show fillings',
    inStock: true,
  },

  // ── All Day Breakfast ─────────────────────────────────────
  {
    id: 'tapa-kimchilog',
    name: 'Tapa & Kimchilog',
    description: 'Filipino beef tapa with kimchi, garlic rice, and egg.',
    longDescription: 'Filipino beef tapa paired with tangy kimchi, fragrant garlic rice, and a perfectly cooked egg — a fusion silog worth waking up for.',
    price: 333,
    tags: ['breakfast'],
    category: 'All Day Breakfast',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Tapa and Kimchilog — beef tapa with kimchi, garlic rice, and egg',
    inStock: true,
  },
  {
    id: 'embonisa-silog',
    name: 'Embonisa at Silog',
    description: 'Classic Filipino embutido with fried rice and egg.',
    longDescription: 'Classic homestyle embutido served with garlic fried rice and egg — a hearty, all-day Filipino breakfast.',
    price: 260,
    tags: ['breakfast'],
    category: 'All Day Breakfast',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Embonisa at Silog — embutido with garlic rice and egg',
    inStock: true,
  },

  // ── Mains ─────────────────────────────────────────────────
  {
    id: 'kalderetang-baka',
    name: 'Kalderetang Baka',
    description: 'Classic Filipino beef stew.',
    longDescription: 'Rich, slow-cooked Filipino beef kaldereta — tender beef in a tomato-based sauce with vegetables, just like home.',
    price: 353,
    tags: ['main'],
    category: 'Mains',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Kalderetang Baka — classic Filipino beef stew',
    inStock: true,
  },
  {
    id: 'spicy-pork-sisig',
    name: 'Spicy Pork Sisig',
    description: 'Authentic Kapampangan sisig.',
    longDescription: 'Authentic Kapampangan sisig — chopped, sizzling, and spiced just right. The dish that put Pampanga on the culinary map.',
    price: 247,
    tags: ['main', 'bestseller'],
    category: 'Mains',
    image: '/assets/photos/533031822_1345498534246998_2146053979510666328_n.jpg',
    imageAlt: 'Hola Spicy Pork Sisig — chopped sizzling pork sisig with chili and calamansi, served with a bowl of garlic rice and dipping sauce',
    inStock: true,
  },
  {
    id: 'pork-belly-kilayin',
    name: 'Pork Belly Kilayin',
    description: 'Filipino stew in vinegar, fish sauce, garlic, and banana.',
    longDescription: 'A Kapampangan classic — pork belly slow-cooked in vinegar, fish sauce, and lots of garlic, served with pan-seared banana.',
    price: 293,
    tags: ['main'],
    category: 'Mains',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Pork Belly Kilayin — Kapampangan stew with garlic and banana',
    inStock: true,
  },
  {
    id: 'fried-chicken-roll',
    name: 'Fried Chicken Roll',
    description: 'Breaded chicken rolls stuffed with ham and cheese.',
    longDescription: 'Deep-fried breaded chicken rolls stuffed with ham and cheese, served with a creamy cheese sauce on the side.',
    price: 320,
    tags: ['main'],
    category: 'Mains',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Fried Chicken Roll — breaded chicken stuffed with ham and cheese',
    inStock: true,
  },
  {
    id: 'papas-chicken-curry',
    name: "Papa's Chicken Curry",
    description: 'Pinoy style creamy chicken curry.',
    longDescription: "Papa's creamy Pinoy-style chicken curry — warm, fragrant, and comforting with every spoonful.",
    price: 327,
    tags: ['main'],
    category: 'Mains',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: "Papa's Chicken Curry — creamy Filipino-style chicken curry",
    inStock: true,
  },
  {
    id: 'chicken-shawarma-rice-bowl',
    name: 'Chicken Shawarma Rice Bowl',
    description: 'Chicken shawarma served in a bowl.',
    longDescription: 'Seasoned chicken shawarma over rice — a satisfying, flavor-packed bowl you can enjoy any time of day.',
    price: 260,
    tags: ['main'],
    category: 'Mains',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Chicken Shawarma Rice Bowl — shawarma chicken over rice',
    inStock: true,
  },
  {
    id: 'baked-chicken-adobo',
    name: 'Baked Chicken Adobo',
    description: 'Chicken quarters baked in rich adobo sauce with egg.',
    longDescription: 'Chicken quarters baked low and slow in rich adobo sauce until deeply flavored — served with egg for the full Filipino comfort meal.',
    price: 293,
    tags: ['main'],
    category: 'Mains',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Baked Chicken Adobo — chicken in adobo sauce with egg',
    inStock: true,
  },

  // ── Pasta ─────────────────────────────────────────────────
  {
    id: 'chicken-pesto',
    name: 'Chicken Pesto',
    description: 'Tender chicken tossed in basil pesto pasta.',
    longDescription: 'Tender, juicy chicken tossed with al dente pasta in a vibrant basil pesto sauce.',
    price: 247,
    tags: ['pasta'],
    category: 'Pasta',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Chicken Pesto — chicken with basil pesto pasta',
    inStock: true,
  },

  // ── Hola Ensaymadness (Box of 6) ─────────────────────────
  {
    id: 'ensaymadness',
    name: 'Ensaymadness',
    description: 'Soft, buttery ensaymada topped with grated cheese — the hero SKU.',
    longDescription: 'Take a sweet break and indulge in the soft, buttery goodness of our Ensaymadness! Generously topped with grated cheese and baked to pillowy perfection — perfect with your favorite drink and guaranteed to make any day extra special.',
    price: 440,
    priceNote: 'Box of 6 pcs',
    tags: ['bestseller', 'ensaymada', 'coffee-pairing'],
    category: 'Ensaymadness',
    image: '/assets/photos/599940003_1457813383015512_5432301823276662530_n.jpg',
    imageAlt: 'Hola Ensaymadness — six pillow-soft ensaymada rolls piled with grated cheese and cream drizzle, in an open yellow Hola box',
    inStock: true,
  },
  {
    id: 'hola-cream-cheese',
    name: 'Hola Cream Cheese',
    description: 'Sweet, fluffy pastry filled with cream cheese, topped with a sugary glaze.',
    longDescription: 'The Original HOLA Creamcheese Ensaymadness — freshly baked, cheesy, pillow soft bread, generously filled, genuine and authentic Kapampangan.',
    price: 440,
    priceNote: 'Box of 6 pcs',
    tags: ['bestseller', 'ensaymada', 'cheese', 'coffee-pairing'],
    category: 'Ensaymadness',
    image: '/assets/photos/fp_26527666_cream-cheese-ensaymadness.jpg',
    imageAlt: 'Hola Cream Cheese Ensaymadness — six pillow-soft ensaymada rolls blanketed in fine grated cheese with cream drizzle, in an open yellow Hola box',
    inStock: true,
  },
  {
    id: 'assorted-ensaymadness',
    name: 'Hola Assorted Ensaymadness',
    description: 'Yema, ube, salted egg, cheesecake, butter, and Bavarian.',
    longDescription: 'Six ensaymada in one box — yema, ube, salted egg, cheesecake, butter, and Bavarian. The full Hola Ensaymadness experience.',
    price: 420,
    priceNote: 'Box of 6 pcs',
    tags: ['bestseller', 'ensaymada', 'ube', 'gifting'],
    category: 'Ensaymadness',
    image: '/assets/photos/fp_26527668_assorted-ensaymadness.jpg',
    imageAlt: 'Hola Assorted Ensaymadness — six ensaymada rolls in assorted flavors blanketed in grated cheese with purple ube pieces, in an open yellow Hola box',
    inStock: true,
  },

  // ── Hola Bars ─────────────────────────────────────────────
  {
    id: 'ensaymaditas',
    name: 'Hola Ensaymaditas',
    description: 'Mini ensaymada topped with butter, sugar, and cheese.',
    longDescription: 'Fifteen mini ensaymada treats — soft, fluffy, and topped with butter, sugar, and cheese. Perfect for sharing or a sweet afternoon treat.',
    price: 300,
    priceNote: 'Box of 15 pcs',
    tags: ['ensaymada', 'everyday', 'gifting'],
    category: 'Hola Bars',
    image: '/assets/photos/732165090_994774773335861_1501598978674623635_n.jpg',
    imageAlt: 'Hola Ensaymaditas — fifteen mini ensaymada covered in grated cheese with cream drizzle, packed in an open yellow Hola box',
    inStock: true,
  },

  // ── Hot Beverages (12oz) ──────────────────────────────────
  {
    id: 'americano',
    name: 'Americano',
    description: 'Bold and smooth black coffee.',
    longDescription: 'Bold, smooth black coffee — simple, honest, and the perfect pair for any Hola bread.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks', 'coffee-pairing', 'everyday'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Americano — bold black coffee in a branded yellow cup',
    inStock: true,
  },
  {
    id: 'cafe-latte',
    name: 'Cafe Latte',
    description: 'Espresso with silky steamed milk.',
    longDescription: 'Smooth espresso shots pulled fresh and blended with silky steamed milk.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks', 'coffee-pairing'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Cafe Latte — espresso with steamed milk',
    inStock: true,
  },
  {
    id: 'spanish-latte',
    name: 'Spanish Latte',
    description: 'Sweet and creamy espresso blended with milk.',
    longDescription: 'A sweet, creamy espresso latte — the Hola spin on a Filipino café favorite.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks', 'coffee-pairing'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Spanish Latte — sweet creamy espresso',
    inStock: true,
  },
  {
    id: 'mocha',
    name: 'Mocha',
    description: 'Rich mix of coffee and chocolate.',
    longDescription: 'A rich, warming blend of espresso and chocolate — coffee and dessert in one cup.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Mocha — rich coffee and chocolate blend',
    inStock: true,
  },
  {
    id: 'caramel-macchiato',
    name: 'Caramel Macchiato',
    description: 'Espresso with caramel and milk layers.',
    longDescription: 'Layered espresso, steamed milk, and sweet caramel drizzle — beautifully balanced.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Caramel Macchiato — layered espresso with caramel',
    inStock: true,
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    description: 'Espresso topped with frothy milk foam.',
    longDescription: 'Classic cappuccino — bold espresso topped with a generous cloud of frothy milk foam.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Cappuccino — espresso with frothy milk foam',
    inStock: true,
  },
  {
    id: 'white-chocolate-mocha',
    name: 'White Chocolate Mocha',
    description: 'Espresso blended with sweet white chocolate.',
    longDescription: 'Smooth espresso blended with sweet white chocolate for a creamy, indulgent cup.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola White Chocolate Mocha — espresso with white chocolate',
    inStock: true,
  },
  {
    id: 'milo-latte',
    name: 'Milo Latte',
    description: 'Creamy latte with a Milo twist.',
    longDescription: 'A creamy hot latte with the beloved Milo flavor — nostalgic, comforting, and unmistakably Filipino.',
    price: 172,
    priceNote: '12oz',
    tags: ['hot-drinks'],
    category: 'Hot Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Milo Latte — creamy latte with Milo',
    inStock: true,
  },

  // ── Over Ice (16oz) ───────────────────────────────────────
  {
    id: 'iced-latte',
    name: 'Iced Latte',
    description: 'Smooth espresso with chilled milk.',
    longDescription: 'Smooth espresso over ice with chilled milk — refreshing and perfectly balanced.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks', 'coffee-pairing'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced Latte — espresso with chilled milk over ice',
    inStock: true,
  },
  {
    id: 'iced-cappuccino',
    name: 'Iced Cappuccino',
    description: 'Bold espresso topped with frothy iced milk.',
    longDescription: 'Bold espresso over ice, topped with frothy cold milk for a refreshing cappuccino experience.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced Cappuccino — bold espresso with frothy iced milk',
    inStock: true,
  },
  {
    id: 'iced-mocha',
    name: 'Iced Mocha',
    description: 'Coffee blended with rich chocolate over ice.',
    longDescription: 'Rich chocolate and espresso blended over ice — a chilled indulgence.',
    price: 187,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced Mocha — coffee and chocolate over ice',
    inStock: true,
  },
  {
    id: 'iced-americano',
    name: 'Iced Americano',
    description: 'Strong and refreshing black coffee on ice.',
    longDescription: 'Strong, clean black coffee poured over ice — bold and refreshing.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks', 'everyday'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced Americano — black coffee over ice',
    inStock: true,
  },
  {
    id: 'iced-caramel-macchiato',
    name: 'Iced Caramel Macchiato',
    description: 'Sweet caramel layered with espresso and milk.',
    longDescription: 'Sweet caramel, espresso, and milk layered over ice — sip through the layers.',
    price: 187,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced Caramel Macchiato — caramel, espresso, and milk over ice',
    inStock: true,
  },
  {
    id: 'iced-spanish-latte',
    name: 'Iced Spanish Latte',
    description: 'Creamy sweet latte with a Spanish twist, over ice.',
    longDescription: 'Sweet, creamy Spanish latte served cold over ice — a Hola café staple.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced Spanish Latte — creamy sweet latte over ice',
    inStock: true,
  },
  {
    id: 'iced-white-choco-mocha',
    name: 'Iced White Chocolate Mocha',
    description: 'Espresso with sweet white chocolate and milk, over ice.',
    longDescription: 'Sweet white chocolate and espresso over ice with milk — smooth, rich, and refreshing.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced White Chocolate Mocha — white chocolate espresso over ice',
    inStock: true,
  },
  {
    id: 'iced-milo-latte',
    name: 'Iced Milo Latte',
    description: 'Chilled latte blended with Milo flavor.',
    longDescription: 'Chilled latte with the nostalgic Milo flavor — cold, creamy, and comforting.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Iced Milo Latte — chilled Milo latte',
    inStock: true,
  },
  {
    id: 'coffee-float',
    name: 'Coffee Float',
    description: 'Iced coffee topped with a scoop of ice cream.',
    longDescription: 'Iced coffee crowned with a melting scoop of ice cream — two classics, one cup.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Coffee Float — iced coffee with ice cream scoop',
    inStock: true,
  },
  {
    id: 'vanilla-latte',
    name: 'Vanilla Latte',
    description: 'Smooth latte infused with vanilla sweetness.',
    longDescription: 'Smooth espresso latte delicately infused with vanilla — light, sweet, and easy to love.',
    price: 173,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Vanilla Latte — espresso latte with vanilla',
    inStock: true,
  },
  {
    id: 'double-vanilla',
    name: 'Double Vanilla',
    description: 'Extra creamy vanilla latte indulgence.',
    longDescription: 'Double the vanilla, double the creaminess — for when one shot of sweetness just won\'t do.',
    price: 187,
    priceNote: '16oz',
    tags: ['iced-drinks'],
    category: 'Over Ice',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Double Vanilla — extra creamy vanilla latte',
    inStock: true,
  },

  // ── Holamazing Beverages (16oz) ───────────────────────────
  {
    id: 'chocolate-frappe',
    name: 'Chocolate Frappe',
    description: 'Creamy and chocolatey frozen beverage.',
    longDescription: 'Rich, creamy, chocolatey frozen frappe — thick, indulgent, and totally satisfying.',
    price: 187,
    priceNote: '16oz',
    tags: ['frappe'],
    category: 'Holamazing Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Chocolate Frappe — creamy frozen chocolate beverage',
    inStock: true,
  },
  {
    id: 'mocha-frappe',
    name: 'Mocha Frappe',
    description: 'Coffee and chocolate blended to perfection.',
    longDescription: 'Coffee and chocolate blended into a perfectly frozen frappe — the café classic done Hola-style.',
    price: 187,
    priceNote: '16oz',
    tags: ['frappe'],
    category: 'Holamazing Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Mocha Frappe — coffee and chocolate frappe',
    inStock: true,
  },
  {
    id: 'white-mocha-chips',
    name: 'White Mocha Chips',
    description: 'White chocolate frappe with crunchy chips.',
    longDescription: 'Creamy white chocolate frappe loaded with crunchy chocolate chips — a textural delight.',
    price: 187,
    priceNote: '16oz',
    tags: ['frappe'],
    category: 'Holamazing Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola White Mocha Chips — white chocolate frappe with chips',
    inStock: true,
  },
  {
    id: 'salted-caramel',
    name: 'Salted Caramel',
    description: 'Sweet and salty caramel iced blend.',
    longDescription: 'Sweet caramel meets a hint of salt in this irresistible iced blend — perfectly balanced.',
    price: 187,
    priceNote: '16oz',
    tags: ['frappe'],
    category: 'Holamazing Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola Salted Caramel — sweet and salty caramel frappe',
    inStock: true,
  },
  {
    id: 'white-choco-mocha',
    name: 'White Choco Mocha',
    description: 'Smooth coffee with white chocolate flavor.',
    longDescription: 'Smooth coffee blended with white chocolate for a lush, creamy iced drink.',
    price: 187,
    priceNote: '16oz',
    tags: ['frappe'],
    category: 'Holamazing Beverages',
    image: '/assets/logo/349594746_1694568097629810_5399586794046856493_n.jpg',
    imageAlt: 'Hola White Choco Mocha — coffee with white chocolate',
    inStock: true,
  },

  // ── Non Coffee (16oz) ─────────────────────────────────────
  {
    id: 'cookies-and-cream',
    name: 'Cookies & Cream',
    description: 'Creamy frappe with cookie crunch.',
    longDescription: 'Creamy cookies and cream frappe packed with cookie crunch in every sip.',
    price: 187,
    priceNote: '16oz',
    tags: ['non-coffee', 'frappe'],
    category: 'Non Coffee',
    image: '/assets/photos/598527943_1458476646282519_5204967568052804532_n.jpg',
    imageAlt: 'Hola Non Coffee drinks — colorful iced beverages in branded Hola cups on a tray',
    inStock: true,
  },
  {
    id: 'matcha',
    name: 'Matcha',
    description: 'Earthy green tea blended into a refreshing iced beverage.',
    longDescription: 'Earthy, vibrant matcha blended into a smooth, refreshing iced drink — for the green tea lovers.',
    price: 187,
    priceNote: '16oz',
    tags: ['non-coffee'],
    category: 'Non Coffee',
    image: '/assets/photos/598527943_1458476646282519_5204967568052804532_n.jpg',
    imageAlt: 'Hola Non Coffee drinks — colorful iced beverages in branded Hola cups on a tray',
    inStock: true,
  },
  {
    id: 'choco-loco',
    name: 'Choco Loco',
    description: "Chocolate lover's ultimate iced blend.",
    longDescription: "Chocolate lover's ultimate iced blend — deep, rich, and unabashedly chocolatey.",
    price: 187,
    priceNote: '16oz',
    tags: ['non-coffee', 'frappe'],
    category: 'Non Coffee',
    image: '/assets/photos/598527943_1458476646282519_5204967568052804532_n.jpg',
    imageAlt: 'Hola Non Coffee drinks — colorful iced beverages in branded Hola cups on a tray',
    inStock: true,
  },
  {
    id: 'berry-fresh',
    name: 'Berry Fresh',
    description: 'Refreshing iced beverage with mixed berries.',
    longDescription: 'Light, refreshing, and bursting with mixed berry flavor — the perfect non-coffee cool-down.',
    price: 200,
    priceNote: '16oz',
    tags: ['non-coffee'],
    category: 'Non Coffee',
    image: '/assets/photos/598527943_1458476646282519_5204967568052804532_n.jpg',
    imageAlt: 'Hola Non Coffee drinks — colorful iced beverages in branded Hola cups on a tray',
    inStock: true,
  },
  {
    id: 'lemon-iced-tea',
    name: 'Lemon Iced Tea',
    description: 'Classic zesty lemon tea served iced.',
    longDescription: 'Classic, zesty lemon iced tea — clean, refreshing, and always hits the spot.',
    price: 147,
    priceNote: '16oz',
    tags: ['non-coffee', 'everyday'],
    category: 'Non Coffee',
    image: '/assets/photos/598527943_1458476646282519_5204967568052804532_n.jpg',
    imageAlt: 'Hola Non Coffee drinks — colorful iced beverages in branded Hola cups on a tray',
    inStock: true,
  },
];

// Legacy helper — returns the 4 hero products for the homepage
export const HERO_PRODUCTS = PRODUCTS.filter((p) =>
  ['ensaymadness', 'hola-cream-cheese', 'spicy-pork-sisig', 'americano'].includes(p.id)
);

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: MenuCategory): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}
